@user = User.create(username: "itsme", password: "lawl")
@user1 = User.create(username: "alex", password: "volkson")

@coffee_1 = Coffee.create(name: "arabica_1")
@tea_1 = Tea.create(name: "earl grey 1")
@coffee_2 = Coffee.create(name: "arabica_2")
@tea_2 = Tea.create(name: "earl grey 2")
@coffee_3 = Coffee.create(name: "arabica_3")
@tea_3 = Tea.create(name: "earl grey 3")
@coffee_4 = Coffee.create(name: "arabica_4")
@tea_4 = Tea.create(name: "earl grey 4")
@coffee_5 = Coffee.create(name: "arabica_5")
@tea_5 = Tea.create(name: "earl grey 5")
@coffee_6 = Coffee.create(name: "arabica_6")
@tea_6 = Tea.create(name: "earl grey 6")
