@user = User.create(username: "itsme", password: "lawl")
@user1 = User.create(username: "alex", password: "volkson")

@coffee_1 = Product.create(name: "arabica_1", brand: "some type of coffee", price: 51, category: "coffee")
@tea_1 = Product.create(name: "earl grey 1", brand: "some type of tea", price: 30, category: "tea")
@coffee_2 = Product.create(name: "arabica_2", brand: "some type of coffee", price: 0.50, category: "coffee")
@tea_2 = Product.create(name: "earl grey 2", brand: "some type of tea", price: 14, category: "tea")
@coffee_3 = Product.create(name: "arabica_3", brand: "some type of coffee", price: 11.50, category: "coffee")
@tea_3 = Product.create(name: "earl grey 3", brand: "some type of tea", price: 3.50, category: "tea")
@coffee_4 = Product.create(name: "arabica_4", brand: "some type of coffee", price: 7.50, category: "coffee")
@tea_4 = Product.create(name: "earl grey 4", brand: "some type of tea", price: 6.50, category: "tea")
@coffee_5 = Product.create(name: "arabica_5", brand: "some type of coffee", price: 4.50, category: "coffee")
@tea_5 = Product.create(name: "earl grey 5", brand: "some type of tea", price: 50 ,category: "tea")
@coffee_6 = Product.create(name: "arabica_6", brand: "some type of coffee", price: 1.50, category: "coffee")
@tea_6 = Product.create(name: "earl grey 6", brand: "some type of tea", price: 4.50, category: "tea")